export const countries =[
  { id: 1, label: "Afghanistan", code: "AF" },
  { id: 2, label: "Albania", code: "AL" },
  { id: 3, label: "Algeria", code: "DZ" },
  { id: 4, label: "Andorra", code: "AD" },
  { id: 5, label: "Angola", code: "AO" },
  { id: 6, label: "Antigua and Barbuda", code: "AG" },
  { id: 7, label: "Argentina", code: "AR" },
  { id: 8, label: "Armenia", code: "AM" },
  { id: 9, label: "Australia", code: "AU" },
  { id: 10, label: "Austria", code: "AT" },
  { id: 11, label: "Azerbaijan", code: "AZ" },
  { id: 12, label: "Bahamas", code: "BS" },
  { id: 13, label: "Bahrain", code: "BH" },
  { id: 14, label: "Bangladesh", code: "BD" },
  { id: 15, label: "Barbados", code: "BB" },
  { id: 16, label: "Belarus", code: "BY" },
  { id: 17, label: "Belgium", code: "BE" },
  { id: 18, label: "Belize", code: "BZ" },
  { id: 19, label: "Benin", code: "BJ" },
  { id: 20, label: "Bhutan", code: "BT" },
  { id: 21, label: "Bolivia", code: "BO" },
  { id: 22, label: "Bosnia and Herzegovina", code: "BA" },
  { id: 23, label: "Botswana", code: "BW" },
  { id: 24, label: "Brazil", code: "BR" },
  { id: 25, label: "Brunei", code: "BN" },
  { id: 26, label: "Bulgaria", code: "BG" },
  { id: 27, label: "Burkina Faso", code: "BF" },
  { id: 28, label: "Burundi", code: "BI" },
  { id: 29, label: "Cabo Verde", code: "CV" },
  { id: 30, label: "Cambodia", code: "KH" },
  { id: 31, label: "Cameroon", code: "CM" },
  { id: 32, label: "Canada", code: "CA" },
  { id: 33, label: "Central African Republic", code: "CF" },
  { id: 34, label: "Chad", code: "TD" },
  { id: 35, label: "Chile", code: "CL" },
  { id: 36, label: "China", code: "CN" },
  { id: 37, label: "Colombia", code: "CO" },
  { id: 38, label: "Comoros", code: "KM" },
  { id: 39, label: "Congo", code: "CG" },
  { id: 40, label: "Costa Rica", code: "CR" },
  { id: 41, label: "Croatia", code: "HR" },
  { id: 42, label: "Cuba", code: "CU" },
  { id: 43, label: "Cyprus", code: "CY" },
  { id: 44, label: "Czech Republic", code: "CZ" },
  { id: 45, label: "Denmark", code: "DK" },
  { id: 46, label: "Djibouti", code: "DJ" },
  { id: 47, label: "Dominica", code: "DM" },
  { id: 48, label: "Dominican Republic", code: "DO" },
  { id: 49, label: "Ecuador", code: "EC" },
  { id: 50, label: "Egypt", code: "EG" },
  { id: 51, label: "El Salvador", code: "SV" },
  { id: 52, label: "Equatorial Guinea", code: "GQ" },
  { id: 53, label: "Eritrea", code: "ER" },
  { id: 54, label: "Estonia", code: "EE" },
  { id: 55, label: "Eswatini", code: "SZ" },
  { id: 56, label: "Ethiopia", code: "ET" },
  { id: 57, label: "Fiji", code: "FJ" },
  { id: 58, label: "Finland", code: "FI" },
  { id: 59, label: "France", code: "FR" },
  { id: 60, label: "Gabon", code: "GA" },
  { id: 61, label: "Gambia", code: "GM" },
  { id: 62, label: "Georgia", code: "GE" },
  { id: 63, label: "Germany", code: "DE" },
  { id: 64, label: "Ghana", code: "GH" },
  { id: 65, label: "Greece", code: "GR" },
  { id: 66, label: "Grenada", code: "GD" },
  { id: 67, label: "Guatemala", code: "GT" },
  { id: 68, label: "Guinea", code: "GN" },
  { id: 69, label: "Guinea-Bissau", code: "GW" },
  { id: 70, label: "Guyana", code: "GY" },
  { id: 71, label: "Haiti", code: "HT" },
  { id: 72, label: "Honduras", code: "HN" },
  { id: 73, label: "Hungary", code: "HU" },
  { id: 74, label: "Iceland", code: "IS" },
  { id: 75, label: "India", code: "IN" },
  { id: 76, label: "Indonesia", code: "ID" },
  { id: 77, label: "Iran", code: "IR" },
  { id: 78, label: "Iraq", code: "IQ" },
  { id: 79, label: "Ireland", code: "IE" },
  { id: 80, label: "Israel", code: "IL" },
  { id: 81, label: "Italy", code: "IT" },
  { id: 82, label: "Jamaica", code: "JM" },
  { id: 83, label: "Japan", code: "JP" },
  { id: 84, label: "Jordan", code: "JO" },
  { id: 85, label: "Kazakhstan", code: "KZ" },
  { id: 86, label: "Kenya", code: "KE" },
  { id: 87, label: "Kiribati", code: "KI" },
  { id: 88, label: "Kosovo", code: "XK" },
  { id: 89, label: "Kuwait", code: "KW" },
  { id: 90, label: "Kyrgyzstan", code: "KG" },
  { id: 91, label: "Laos", code: "LA" },
  { id: 92, label: "Latvia", code: "LV" },
  { id: 93, label: "Lebanon", code: "LB" },
  { id: 94, label: "Lesotho", code: "LS" },
  { id: 95, label: "Liberia", code: "LR" },
  { id: 96, label: "Libya", code: "LY" },
  { id: 97, label: "Liechtenstein", code: "LI" },
  { id: 98, label: "Lithuania", code: "LT" },
  { id: 99, label: "Luxembourg", code: "LU" },
  { id: 100, label: "Madagascar", code: "MG" },
  { id: 101, label: "Malawi", code: "MW" },
  { id: 102, label: "Malaysia", code: "MY" },
  { id: 103, label: "Maldives", code: "MV" },
  { id: 104, label: "Mali", code: "ML" },
  { id: 105, label: "Malta", code: "MT" },
  { id: 106, label: "Marshall Islands", code: "MH" },
  { id: 107, label: "Mauritania", code: "MR" },
  { id: 108, label: "Mauritius", code: "MU" },
  { id: 109, label: "Mexico", code: "MX" },
  { id: 110, label: "Micronesia", code: "FM" },
  { id: 111, label: "Moldova", code: "MD" },
  { id: 112, label: "Monaco", code: "MC" },
  { id: 113, label: "Mongolia", code: "MN" },
  { id: 114, label: "Montenegro", code: "ME" },
  { id: 115, label: "Morocco", code: "MA" },
  { id: 116, label: "Mozambique", code: "MZ" },
  { id: 117, label: "Myanmar", code: "MM" },
  { id: 118, label: "Namibia", code: "NA" },
  { id: 119, label: "Nauru", code: "NR" },
  { id: 120, label: "Nepal", code: "NP" },
  { id: 121, label: "Netherlands", code: "NL" },
  { id: 122, label: "New Zealand", code: "NZ" },
  { id: 123, label: "Nicaragua", code: "NI" },
  { id: 124, label: "Niger", code: "NE" },
  { id: 125, label: "Nigeria", code: "NG" },
  { id: 126, label: "North Korea", code: "KP" },
  { id: 127, label: "North Macedonia", code: "MK" },
  { id: 128, label: "Norway", code: "NO" },
  { id: 129, label: "Oman", code: "OM" },
  { id: 130, label: "Pakistan", code: "PK" },
  { id: 131, label: "Palau", code: "PW" },
  { id: 132, label: "Palestine", code: "PS" },
  { id: 133, label: "Panama", code: "PA" },
  { id: 134, label: "Papua New Guinea", code: "PG" },
  { id: 135, label: "Paraguay", code: "PY" },
  { id: 136, label: "Peru", code: "PE" },
  { id: 137, label: "Philippines", code: "PH" },
  { id: 138, label: "Poland", code: "PL" },
  { id: 139, label: "Portugal", code: "PT" },
  { id: 140, label: "Qatar", code: "QA" },
  { id: 141, label: "Romania", code: "RO" },
  { id: 142, label: "Russia", code: "RU" },
  { id: 143, label: "Rwanda", code: "RW" },
  { id: 144, label: "Saint Kitts and Nevis", code: "KN" },
  { id: 145, label: "Saint Lucia", code: "LC" },
  { id: 146, label: "Saint Vincent and the Grenadines", code: "VC" },
  { id: 147, label: "Samoa", code: "WS" },
  { id: 148, label: "San Marino", code: "SM" },
  { id: 149, label: "Sao Tome and Principe", code: "ST" },
  { id: 150, label: "Saudi Arabia", code: "SA" },
  { id: 151, label: "Senegal", code: "SN" },
  { id: 152, label: "Serbia", code: "RS" },
  { id: 153, label: "Seychelles", code: "SC" },
  { id: 154, label: "Sierra Leone", code: "SL" },
  { id: 155, label: "Singapore", code: "SG" },
  { id: 156, label: "Slovakia", code: "SK" },
  { id: 157, label: "Slovenia", code: "SI" },
  { id: 158, label: "Solomon Islands", code: "SB" },
  { id: 159, label: "Somalia", code: "SO" },
  { id: 160, label: "South Africa", code: "ZA" },
  { id: 161, label: "South Korea", code: "KR" },
  { id: 162, label: "South Sudan", code: "SS" },
  { id: 163, label: "Spain", code: "ES" },
  { id: 164, label: "Sri Lanka", code: "LK" },
  { id: 165, label: "Sudan", code: "SD" },
  { id: 166, label: "Suriname", code: "SR" },
  { id: 167, label: "Sweden", code: "SE" },
  { id: 168, label: "Switzerland", code: "CH" },
  { id: 169, label: "Syria", code: "SY" },
  { id: 170, label: "Taiwan", code: "TW" },
  { id: 171, label: "Tajikistan", code: "TJ" },
  { id: 172, label: "Tanzania", code: "TZ" },
  { id: 173, label: "Thailand", code: "TH" },
  { id: 174, label: "Timor-Leste", code: "TL" },
  { id: 175, label: "Togo", code: "TG" },
  { id: 176, label: "Tonga", code: "TO" },
  { id: 177, label: "Trinidad and Tobago", code: "TT" },
  { id: 178, label: "Tunisia", code: "TN" },
  { id: 179, label: "Turkey", code: "TR" },
  { id: 180, label: "Turkmenistan", code: "TM" },
  { id: 181, label: "Tuvalu", code: "TV" },
  { id: 182, label: "Uganda", code: "UG" },
  { id: 183, label: "Ukraine", code: "UA" },
  { id: 184, label: "United Arab Emirates", code: "AE" },
  { id: 185, label: "United Kingdom", code: "GB" },
  { id: 186, label: "United States of America", code: "US" },
  { id: 187, label: "Uruguay", code: "UY" },
  { id: 188, label: "Uzbekistan", code: "UZ" },
  { id: 189, label: "Vanuatu", code: "VU" },
  { id: 190, label: "Vatican City", code: "VA" },
  { id: 191, label: "Venezuela", code: "VE" },
  { id: 192, label: "Vietnam", code: "VN" },
  { id: 193, label: "Yemen", code: "YE" },
  { id: 194, label: "Zambia", code: "ZM" },
  { id: 195, label: "Zimbabwe", code: "ZW" },
];
